import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";
import { MoviesProvider } from "@/app/_components/MoviesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Browse Movies or TV Series",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navigation />
        <MoviesProvider>{children}</MoviesProvider>
      </body>
    </html>
  );
}

// Copyright By Giorgi Kakauridze
